export const PRODUCT_KEYS = {
  name: 'Product Name',
  price: 'Price',
  modelName: 'Model Name',
  color: 'Color',
  displaySize: 'Display Size',
  screenType: 'Screen Type',
  refreshRate: 'Refresh Rate',
  resolution: 'Resolution',
  smartTv: 'Smart TV',
  curveTv: 'Curve TV',
  wifiSupport: 'Built in Wi-fi',
  series: 'Series',
  launchYear: 'Launch Year',
  maxQuantity: 'Max Quantity',
};
export const PRODUCTS = {
  sony1: {
    name: 'Sony Bravia R202G 80cm (32 inch) HD Ready LED TV  (KLV-32R202G)',
    price: 20000,
    modelName: 'KLV-32R202G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'No',
    curveTv: 'No',
    wifiSupport: 'No',
    series: 'Bravia R202G',
    launchYear: '2019',
    maxQuantity: 10,
  },
  sony2: {
    name: 'Sony Bravia R202G 100cm (40 inch) HD Ready LED TV  (KLV-33R202G)',
    price: 22000,
    modelName: 'KLV-32R203G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'Yes',
    curveTv: 'No',
    wifiSupport: 'Yes',
    series: 'Bravia R202G',
    launchYear: '2020',
    maxQuantity: 10,
  },
  samsung1: {
    name: 'Samsung Bravia D202G 80cm (32 inch) HD Ready LED TV  (KLV-42R202G)',
    price: 20000,
    modelName: 'KLV-32R202G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'No',
    curveTv: 'No',
    wifiSupport: 'No',
    series: 'Bravia R202G',
    launchYear: '2019',
    maxQuantity: 10,
  },
  samsung2: {
    name: 'Samsung Bravia C202G 100cm (40 inch) HD Ready LED TV  (KLV-53R202G)',
    price: 22000,
    modelName: 'KLV-32R203G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'Yes',
    curveTv: 'No',
    wifiSupport: 'Yes',
    series: 'Bravia R202G',
    launchYear: '2020',
    maxQuantity: 10,
  },
  LG2: {
    name: 'LG B202G 80cm (32 inch) HD Ready LED TV  (KLV-22R202G)',
    price: 20000,
    modelName: 'KLV-32R202G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'No',
    curveTv: 'No',
    wifiSupport: 'No',
    series: 'Bravia R202G',
    launchYear: '2019',
    maxQuantity: 10,
  },
  LG1: {
    name: 'LG A202G 100cm (40 inch) HD Ready LED TV  (KLV-63R202G)',
    price: 22000,
    modelName: 'KLV-32R203G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'Yes',
    curveTv: 'No',
    wifiSupport: 'Yes',
    series: 'Bravia R202G',
    launchYear: '2020',
    maxQuantity: 10,
  },

  MI2: {
    name: 'MI 4B 80cm (32 inch) HD Ready LED TV  (KLV-22R202G)',
    price: 20000,
    modelName: 'KLV-32R202G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'No',
    curveTv: 'No',
    wifiSupport: 'No',
    series: 'Bravia R202G',
    launchYear: '2019',
    maxQuantity: 10,
  },
  MI1: {
    name: 'MI 4A 100cm (40 inch) HD Ready LED TV  (KLV-63R202G)',
    price: 22000,
    modelName: 'KLV-32R203G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'Yes',
    curveTv: 'No',
    wifiSupport: 'Yes',
    series: 'Bravia R202G',
    launchYear: '2020',
    maxQuantity: 10,
  },
  MI1: {
    name: 'Sansui 100cm (40 inch) HD Ready LED TV  (KLV-63R202G)',
    price: 22000,
    modelName: 'MLV-32R203G',
    color: 'Black',
    displaySize: '80 cm (32)',
    screenType: 'LED',
    refreshRate: '50Hz',
    resolution: 'HD Ready, 1366 x 768',
    smartTv: 'Yes',
    curveTv: 'No',
    wifiSupport: 'Yes',
    series: 'Bravia R202G',
    launchYear: '2020',
    maxQuantity: 10,
  },

};
